image: node:16.13.0

pipelines:
  branches:
    master:
      - step:
          name: Build and test
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy to MAIN
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $SSH_USER
                SERVER: $SSH_SERVER
                REMOTE_PATH: '/home/admin2/docker-containers/ruqi-cdn-node/public_html'
                LOCAL_PATH: 'dist/*'
                DEBUG: 'true'
    dev:
      - step:
          name: Build and test
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy to DEV
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $SSH_USER
                SERVER: $SSH_SERVER
                REMOTE_PATH: '/home/admin2/docker-containers/ruqi-cdn-node/public_html'
                LOCAL_PATH: 'dist/*'
                DEBUG: 'true'
